apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://helm.datadoghq.com
      chart: datadog
      targetRevision: "3.164.0"
      helm:
        valueFiles:
          - $values/monitoring/datadog/values.yaml

    - repoURL: https://github.com/vitaliscode/rd-task-tracker.git
      targetRevision: ops
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: datadog

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true