apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rd-frontend-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/vitaliscode/rd-task-tracker.git
    targetRevision: main
    path: helm/frontend
    helm:
      valueFiles:
        - values-stage.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: rd-staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 30s