name: Build-Cscan-Push-API

on:
  workflow_call:

# env:
#   AWS_REGION: ${{ secrets.AWS_REGION }}
#   AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
#   ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}

#   API_IMAGE: ${{ secrets.ECR_REGISTRY }}/rd-task-tracker/api
#   FRONTEND_IMAGE: ${{ secrets.ECR_REGISTRY }}/rd-task-tracker/frontend

jobs:
  build-cscan-push-api:
    name: Build, ContainerScan, Push API
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: github-actions

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login \
          --username AWS \
          --password-stdin \
          ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

      - name: Set Image Tag
        run: echo "SHORT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Build API Docker Image
        run: |
          docker build \
            --target production \
            -t $API_IMAGE:$SHORT_SHA \
            -t $API_IMAGE:latest \
            services/api/

      - name: Scan API Image with Trivy
        continue-on-error: true
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ env.API_IMAGE }}:${{ env.SHORT_SHA }}
          format: table
          severity: HIGH,CRITICAL
          exit-code: 1

      - name: Push API Image
        run: |
          docker push $API_IMAGE:$SHORT_SHA
          docker push $API_IMAGE:latest
