name: Security Review

on:
  workflow_call:

jobs:
  # security-review bandit reports are uploaded as artifacts and 
  # can be reviewed by the security team to ensure that any identified vulnerabilities are addressed before deployment. 
  security-review:
    name: Await Security Review Approval
    runs-on: ubuntu-latest       

    environment:
      name: security-review

    steps:
      - name: Await Approval
        run: echo "Security review approved"