image:
  repository: 986232522384.dkr.ecr.eu-central-1.amazonaws.com/rd-task-tracker/frontend
  tag: 055d0046
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb


resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi


probes:
  liveness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 15
  readiness:
    path: /health
    initialDelaySeconds: 3
    periodSeconds: 10
