image:
  repository: 986232522384.dkr.ecr.eu-central-1.amazonaws.com/rd-task-tracker/frontend
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

probes:
  liveness:
    path: /
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

  readiness:
    path: /
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 5
    failureThreshold: 3