replicaCount: 1

image:

  repository: 906462447398.dkr.ecr.eu-central-1.amazonaws.com/rd-task-tracker/frontend
main
  tag: latest

env:
  ENVIRONMENT: staging

# replicaCount: 1

# image:
#   repository: 102364304164.dkr.ecr.eu-central-1.amazonaws.com/rd-task-tracker/frontend
#   tag: latest

# env:
#   ENVIRONMENT: staging